/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Animal = IDL.Record({
  'id' : IDL.Nat,
  'birthDate' : IDL.Text,
  'removedDate' : IDL.Opt(IDL.Text),
  'createdAt' : Time,
  'number' : IDL.Text,
  'animalType' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAnimal' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'deleteAnimal' : IDL.Func([IDL.Nat], [], []),
  'getAnimals' : IDL.Func([], [IDL.Vec(Animal)], ['query']),
  'setRemovedDate' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateAnimal' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Animal = IDL.Record({
    'id' : IDL.Nat,
    'birthDate' : IDL.Text,
    'removedDate' : IDL.Opt(IDL.Text),
    'createdAt' : Time,
    'number' : IDL.Text,
    'animalType' : IDL.Text,
  });
  
  return IDL.Service({
    'addAnimal' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteAnimal' : IDL.Func([IDL.Nat], [], []),
    'getAnimals' : IDL.Func([], [IDL.Vec(Animal)], ['query']),
    'setRemovedDate' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateAnimal' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };